#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
n1 = 1
n2 = 2
nn = 0
sum = 2
max = 4000000
while (nn < max) do
  nn = n1 + n2
  sum += nn if(nn % 2 == 0)
  n1 = n2
  n2 = nn
end

p sum