<<-COMMENT
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
COMMENT

limit = 4_000_000
fib = 0
previous = 0
current = 1
sum = 0

while(fib <= limit) do
  fib = current + previous
  previous = current
  current = fib
  sum += fib if fib % 2 == 0
end

puts sum