#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

ctr = 0
sum = 1
prev = 1
x = 0

until prev >= 1000 do
  sum = sum + prev
  if sum % 2 == 0
    x = x + sum
  end
  ctr += 1
  prev = ctr

end


p x